name: CI

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version.
        type: string
        required: false
        default: "18"
      pnpm-version:
        description: pnpm version.
        type: string
        required: false
        default: "8"
      java-version:
        description: Java version.
        type: string
        required: false
        default: "17"
      ui-path:
        description: Path of UI project.
        type: string
        required: false
        default: "console"
      skip-node-setup:
        description: Indicates if the node setup should be skipped.
        type: boolean
        required: false
        default: false
      artifacts-path:
        type: string
        required: false
        default: build/libs
        description: Artifacts path, default is build/libs. Must be a folder.

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        uses: halo-sigs/actions/plugin-setup-env@v1
        with:
          cache-dept-path: ${{ inputs.ui-path }}/pnpm-lock.yaml
          skip-node-setup: ${{ inputs.skip-node-setup }}
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}
          java-version: ${{ inputs.java-version }}
      - name: Check
        run: ./gradlew clean build
      - name: Upload Artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{ inputs.artifacts-path }}
          retention-days: 1